Layout/EndOfLine:
  Enabled: false

Layout/LineLength:
  Max: 250

Metrics/MethodLength:
  Max: 30

Metrics/ModuleLength:
  Max: 200

Metrics/ClassLength:
  Max: 200

Metrics/AbcSize:
  Max: 30

Metrics/BlockLength:
  Max: 60

Metrics/CyclomaticComplexity:
  Max: 10

Style/Documentation:
  Enabled: false

Style/GlobalVars:
  Enabled: false

AllCops:
  TargetRubyVersion: 2.6

Style/FrozenStringLiteralComment:
  Enabled: false

Security/Eval:
  Enabled: false

Naming/VariableName:
  Enabled: false